---
- name: Elastic Search
  hosts: all
  connection: local
  become: true
  roles:
    - name: elastic.elasticsearch
      es_instance_name: es-dev
      es_config: {
        http.host: 0.0.0.0,
        http.port: 9200,
        transport.tcp.port: 9300,
        index.query.bool.max_clause_count: 16384    # devdocs specifies 10024 for catalogs with > 40k SKUs, need higher
      }
