---
- name: PerconaDB
  hosts: all
  connection: local
  become: true
  vars:
    mysql_server_package_name: Percona-Server-server-{{ mysql_version }}
    mysql_client_package_name: Percona-Server-client-{{ mysql_version }}

  roles:
    - alpacaglue.repo-percona

  tasks:
    - name: Upload /etc/
      copy:
        src: files/percona/etc/
        dest: /etc/

    - name: Uploading init-mysql.sh
      template:
        src: init-mysql.sh
        dest: /usr/local/bin/init-mysql.sh
        owner: root
        group: root
        mode: 0700

    - name: Initialize mysql data
      command: /usr/local/bin/init-mysql.sh
      args:
        creates: /var/lib/mysql/ibdata1

    # Ensures Percona is installed when init procedure isn't needed
    - name: Install Percona Client/Server
      package:
        name: "{{ item }}"
        state: present
      with_items:
         - "{{ mysql_client_package_name }}"
         - "{{ mysql_server_package_name }}"

    - name: Start mysql service
      service:
        name: mysqld
        state: started
        enabled: no     # no auto-starting after reboot (i.e. halt, up); provisioner starts it after data is mounted

    - name: Install python-mysqldb
      package:
        name: MySQL-python
        state: present

    - name: Configuring mysql root user
      mysql_user:
        user: root
        host: "{{ item }}"
        priv: "*.*:ALL,GRANT"
      with_items:
        - localhost
        - dev-host
        - dev-web72
        - dev-web71
        - dev-web70
        - dev-web56
        - dev-web55
