---
- name: configure redis-{{ redis_instance.name }} service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: redis/redis.conf
      dest: /etc/redis/redis-{{ redis_instance.name }}.conf
      mode: "0644"
    - src: init.d/redis.j2
      dest: /etc/init.d/redis-{{ redis_instance.name }}
      mode: "0755"
  register: redis_config_changed
  notify: restart redis
